"use client";

import { useEffect, useState } from "react";
import { Sparkles, Loader2 } from "lucide-react";
import { AuditResult } from "@/types/audit";

type AiSummaryCardProps = {
    result: AuditResult;
    toolsUsed: string[];
};

/**
 * Generates a local fallback summary when the Gemini API is unavailable
 * (e.g. rate-limited, network error, etc.)
 */
function generateLocalSummary(result: AuditResult, toolsUsed: string[]): string {
    const lines: string[] = [];

    // Overspending observation
    if (result.estimatedMonthlyWaste > 0) {
        lines.push(
            `Your current stack of ${toolsUsed.join(", ")} shows approximately $${result.estimatedMonthlyWaste}/month in overlapping subscriptions, adding up to ~$${result.estimatedAnnualSavings.toLocaleString()} annually.`
        );
    } else {
        lines.push(
            `Your tool selection (${toolsUsed.join(", ")}) appears well-optimized with minimal overlap.`
        );
    }

    // Optimization opportunity
    if (result.optimizationScore < 90) {
        lines.push(
            `With an optimization score of ${result.optimizationScore}%, there's room to consolidate redundant tools. Consider standardizing on one primary AI assistant and one coding copilot to reclaim margin.`
        );
    } else {
        lines.push(
            `Your optimization score of ${result.optimizationScore}% indicates a lean, efficient stack. Keep monitoring usage as your team scales.`
        );
    }

    // Recommendation tone
    if (result.recommendations.length > 0) {
        lines.push(
            `We identified ${result.recommendations.length} actionable recommendation${result.recommendations.length > 1 ? "s" : ""} above — addressing these could significantly reduce your infrastructure spend.`
        );
    }

    return lines.join("\n\n");
}

export default function AiSummaryCard({ result, toolsUsed }: AiSummaryCardProps) {
    const [summary, setSummary] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const [source, setSource] = useState<"gemini" | "local">("gemini");

    useEffect(() => {
        async function fetchSummary() {
            try {
                const res = await fetch("/api/ai-summary", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                        toolsUsed,
                        estimatedMonthlyWaste: result.estimatedMonthlyWaste,
                        estimatedAnnualSavings: result.estimatedAnnualSavings,
                        optimizationScore: result.optimizationScore,
                    }),
                });

                const data = await res.json();

                if (data.success && data.summary) {
                    setSummary(data.summary);
                    setSource("gemini");
                } else {
                    // API returned error — use local fallback
                    setSummary(generateLocalSummary(result, toolsUsed));
                    setSource("local");
                }
            } catch {
                // Network/fetch error — use local fallback
                setSummary(generateLocalSummary(result, toolsUsed));
                setSource("local");
            } finally {
                setLoading(false);
            }
        }

        fetchSummary();
    }, [result, toolsUsed]);

    return (
        <div className="relative overflow-hidden rounded-2xl border bg-gradient-to-br from-violet-50 via-card to-fuchsia-50 shadow-sm">
            {/* Decorative glow */}
            <div className="pointer-events-none absolute -right-16 -top-16 h-40 w-40 rounded-full bg-violet-200/30 blur-3xl" />
            <div className="pointer-events-none absolute -left-16 -bottom-16 h-40 w-40 rounded-full bg-fuchsia-200/30 blur-3xl" />

            <div className="relative z-10 p-6 md:p-8">
                {/* Header */}
                <div className="flex items-center gap-2.5 mb-4">
                    <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-100">
                        <Sparkles className="h-[18px] w-[18px] text-violet-600" />
                    </div>
                    <div>
                        <h3 className="text-sm font-bold tracking-tight">AI-Powered Insight</h3>
                        <p className="text-[11px] text-muted-foreground">
                            {source === "gemini" ? "Generated by Gemini" : "Stack Analysis"}
                        </p>
                    </div>
                </div>

                {/* Content */}
                {loading && (
                    <div className="flex items-center gap-3 py-4">
                        <Loader2 className="h-5 w-5 animate-spin text-violet-500" />
                        <p className="text-sm text-muted-foreground animate-pulse">
                            Analyzing your stack with AI...
                        </p>
                    </div>
                )}

                {summary && (
                    <p className="text-sm leading-relaxed text-foreground/85 whitespace-pre-line">
                        {summary}
                    </p>
                )}
            </div>
        </div>
    );
}
